name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run test coverage
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: true